pim_reference_entity:
  reference_entity:
    attribute:
      attribute:
        error:
          render_list: 'Der opstod en fejl under gengivelsen af "{{ %attribute_code% }}"-attributten'
          render_edit: 'Der opstod en fejl under gengivelsen af "{{ %attribute_code% }}"-attributten, yderligere egenskabsfelter'
    create:
      input:
        label: Etiket
    notification:
      save:
        success: Referenceenhed blev opdateret.
        fail: Der opstod en fejl under gemningen af referenceenheden
      create:
        success: Referenceenhed blev oprettet.
        fail: Der opstod en fejl under oprettelsen af referenceenheden
      delete:
        fail: Der opstod en fejl under sletningen af referenceenheden
  record:
    grid:
      filter:
        counter: '{{ matchesCount }} resultat|{{ matchesCount }} resultater'
        completeness:
          all: ALLE
          'yes': 'JA'
          'no': 'NEJ'
    tab:
      enrich: Berige
    notification:
      save:
        fail: Der opstod en fejl under gemningen af arkivet
      create:
        fail: Der opstod en fejl under oprettelsen af arkivet
      delete:
        fail: Der opstod en fejl under sletningen af arkivet
      delete_all:
        fail: Der opstod en fejl under sletningen af alle referenceenhedens arkiver
  attribute:
    notification:
      list:
        fail: Der opstod en fejl under opdateringen af attribut-listen
      save:
        fail: Der opstod en fejl under gemningen af attributten
      create:
        fail: Der opstod en fejl under oprettelsen af attributten
      delete:
        fail: Der opstod en fejl under sletningen af attributten
